version: "3"

services:
  web:
    image: nginx:1.23
    volumes:
      - .:/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - db
      - php

  php:
    build: ./docker
    working_dir: /www
    volumes:
      - .:/www
    links:
      - db
      - redis

  redis:
      image: redis

  adminer:
    image: adminer
    ports:
      - 8081:8080
    links:
      - db

  db:
    image: mariadb:10.11
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=develop
